// Alias dei tipi generati da api/openapi.yaml (npm run gen:api).
import type { components } from './schema'

type Schemas = components['schemas']

export type ErrorCode = Schemas['ErrorCode']
export type StorageType = Schemas['StorageType']
export type Uom = Schemas['Uom']
export type Tracking = Schemas['Tracking']
export type ProductStatus = Schemas['ProductStatus']
export type LotStatus = Schemas['LotStatus']
export type SerialStatus = Schemas['SerialStatus']
export type MovementType = Schemas['MovementType']
export type AdjustmentReason = Schemas['AdjustmentReason']
export type PickStrategy = Schemas['PickStrategy']
export type SalesOrderStatus = Schemas['SalesOrderStatus']
export type PurchaseOrderStatus = Schemas['PurchaseOrderStatus']
export type AlertType = Schemas['AlertType']
export type AlertSeverity = Schemas['AlertSeverity']

export type Warehouse = Schemas['Warehouse']
export type Zone = Schemas['Zone']
export type Location = Schemas['Location']
export type LocationContent = Schemas['LocationContent']
export type Product = Schemas['Product']
export type ProductCreate = Schemas['ProductCreate']
export type ProductUpdate = Schemas['ProductUpdate']
export type ProductListItem = Schemas['ProductListItem']
export type StockFigures = Schemas['StockFigures']
export type ProductAvailability = Schemas['ProductAvailability']
export type Lot = Schemas['Lot']
export type Serial = Schemas['Serial']
export type LotTrace = Schemas['LotTrace']
export type SerialTrace = Schemas['SerialTrace']
export type Shipment = Schemas['Shipment']
export type StockItem = Schemas['StockItem']
export type ReceiptLine = Schemas['ReceiptLine']
export type PickingSuggestion = Schemas['PickingSuggestion']
export type PickingSuggestionLine = Schemas['PickingSuggestionLine']
export type PickInput = Schemas['PickInput']
export type ShipmentLine = Schemas['ShipmentLine']
export type ShipmentRequest = Schemas['ShipmentRequest']
export type OperationResult = Schemas['OperationResult']
export type Movement = Schemas['Movement']
export type SalesOrder = Schemas['SalesOrder']
export type SalesOrderLine = Schemas['SalesOrderLine']
export type SalesOrderResult = Schemas['SalesOrderResult']
export type PurchaseOrder = Schemas['PurchaseOrder']
export type Alert = Schemas['Alert']
